version: '3'
services:
  app:
    restart: always
    image: wanchanok/app:1.1
    container_name: my-app
    ports:
      - ${PORT_APP}:1337
    depends_on:
      - db
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: false
  db:
    image: postgres:latest
    container_name: my-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${DATABASE_PORT}:5432
    # volumes: 
    #   - ./data:/var/lib/postgresql/data
    restart: always
